# Generated by Django 3.2.6 on 2021-08-24 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumnos',
            fields=[
                ('AlumnoId', models.AutoField(primary_key=True, serialize=False)),
                ('AlumnoName', models.CharField(max_length=50)),
                ('Documento', models.CharField(default='Some String', max_length=50)),
                ('DateOfJoining', models.DateField()),
                ('Note', models.CharField(default='Some String', max_length=10)),
                ('PhotoFileName', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['AlumnoId'],
            },
        ),
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('CursoId', models.AutoField(primary_key=True, serialize=False)),
                ('CursoName', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Docentes',
            fields=[
                ('DocenteId', models.AutoField(primary_key=True, serialize=False)),
                ('DocenteName', models.CharField(max_length=50)),
                ('Documento', models.CharField(default='Some String', max_length=50)),
                ('DateOfJoining', models.DateField()),
                ('PhotoFileName', models.CharField(max_length=100)),
                ('alumno', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='InstitutoApp.alumnos')),
                ('curso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='InstitutoApp.cursos')),
            ],
        ),
        migrations.AddField(
            model_name='alumnos',
            name='curso',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, related_name='nameAlumno', to='InstitutoApp.cursos'),
        ),
        migrations.AlterUniqueTogether(
            name='alumnos',
            unique_together={('curso', 'AlumnoId')},
        ),
    ]
